export const catalogItems = [
  {
    name: "Spare Parts Catalog",
    badge: "Featured",
    badgeTone: "primary",
    description: "A structured catalog for motors, filters, bearings, belts, and fast-moving parts.",
    price: "From NPR 1,250",
    tags: ["Catalog", "Parts", "Inventory"],
  },
  {
    name: "Workshop Tools",
    badge: "Ready Stock",
    badgeTone: "success",
    description: "Professional tools and workshop essentials that help keep maintenance work moving.",
    price: "From NPR 850",
    tags: ["Tools", "Workshop", "Operations"],
  },
  {
    name: "Hydraulic Components",
    badge: "High Value",
    badgeTone: "primary",
    description: "Hydraulic hoses, seals, cylinders, and fittings for service and repair workflows.",
    price: "From NPR 3,400",
    tags: ["Hydraulic", "Service", "Repair"],
  },
  {
    name: "Electrical Spares",
    badge: "Popular",
    badgeTone: "success",
    description: "Switches, relays, cables, lamps, and controllers for day-to-day operations.",
    price: "From NPR 690",
    tags: ["Electrical", "Stock", "Catalog"],
  },
  {
    name: "Safety Equipment",
    badge: "Essential",
    badgeTone: "primary",
    description: "Gloves, helmets, boots, and other PPE products that keep people protected on site.",
    price: "From NPR 420",
    tags: ["Safety", "PPE", "Compliance"],
  },
  {
    name: "Service Packages",
    badge: "About",
    badgeTone: "success",
    description: "Warranty and service bundles that pair naturally with the product home page experience.",
    price: "Custom pricing",
    tags: ["About", "Service", "Warranty"],
  },
];
